sudo: false

branches:
   only:
       - release
       - master

language: android

jdk: oraclejdk7

env:
 global:
   - MALLOC_ARENA_MAX=2
   - TERM=dumb
   - ADB_INSTALL_TIMEOUT=12

android:
   components:
       - tools
       - build-tools-23.0.2
       - build-tools-22.2.1
       - android-23
       - android-22
       - android-15
       - extra

script:
   - ./gradlew build connectedCheck
   
notifications:
   slack: mercadopagosdk:RkGMwu92uNzhHtZvylFHZaoO
