sudo: false

branches:
   only:
       - release
       - master

language: android

jdk: oraclejdk7

env:
 global:
   - MALLOC_ARENA_MAX=2
   - TERM=dumb
   - ADB_INSTALL_TIMEOUT=12

android:
   components:
       - tools
       - build-tools-23.0.2
       - android-23
       - android-15
       - extra

script:
   - bash "travis/run_unit_tests.sh"

before_install:
 # Update Ruby version (required for fastlane)
 - rvm install 2.0.0

after_success:
   - bash "travis/run_deploy.sh"

notifications:
   slack: mercadopagosdk:RkGMwu92uNzhHtZvylFHZaoO